# apiVersion: v1
# kind: ServiceAccount
# metadata:
  # name: php-apache
  # namespace: default
---

#apiVersion: extensions/v1beta1
apiVersion: v1
kind: Deployment
metadata:
  name: php-apache
  labels:
    name: php-apache
    topic: staging4.php-apache
  namespace: default
spec:
  replicas: 1
  selector:
    name: php-apache
  template:
    metadata:
      labels:
        name: php-apache
        topic: staging4.php-apache
      namespace: default
    spec:
      containers:
        - name: php-apache
          #image: "135.104.238.154:5000/shoeb/php-apache:v1.0"
          image: "gcr.io/google_containers/hpa-example"
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 200m 
              #cpu: "1" 
          tty: true
          stdin: true
          ports:
            - containerPort: 80
              name: ms-port
---

kind: Service
#apiVersion: extensions/v1beta1
apiVersion: v1
metadata:
  name: php-apache
  labels:
    name: php-apache
    topic: staging4.php-apache
  namespace: default
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
  selector:
    name: php-apache

